# Generated by Django 4.2.23 on 2025-08-20 02:40

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("mojo_app", "Trip")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])



class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0007_modeltripactivity_tripactivitydetails_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
