# Generated by Django 4.2.23 on 2025-08-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0010_alter_trip_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltripactivity',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
