# Generated by Django 4.2.23 on 2025-08-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0011_alter_modeltripactivity_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripactivitydetails',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('rejected', 'Rejected')], default='wishlist', max_length=20),
        ),
    ]
