# Generated by Django 4.2.23 on 2025-08-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0013_alter_tripactivitydetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripactivitydetails',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='mojo_app.trip'),
        ),
    ]
