# Generated by Django 4.2.23 on 2025-09-10 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0015_sharedtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivityComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.modeltripactivity')),
            ],
        ),
    ]
