# Generated by Django 4.2.23 on 2025-09-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0016_tripactivitycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='destination_city',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_state',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
