# Generated by Django 4.2.23 on 2025-09-30 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0017_rename_destination_trip_destination_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.CreateModel(
            name='TripPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_in_trips', to='mojo_app.modeltripactivity')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_plan_items', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='mojo_app.trip')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('trip', 'activity')},
            },
        ),
    ]
