# Generated by Django 4.2.23 on 2025-09-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0018_remove_customuser_is_active_tripplanitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripplanitem',
            options={'ordering': ['position', 'added_at']},
        ),
        migrations.AddField(
            model_name='tripplanitem',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='tripplanitem',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripplanitem',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
