# Generated by Django 4.2.23 on 2025-09-30 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0019_alter_tripplanitem_options_tripplanitem_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripactivitycomment',
            name='plan_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_comments', to='mojo_app.tripplanitem'),
        ),
    ]
