# Generated by Django 4.2.23 on 2025-08-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0004_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('activity_description', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('activity_url', models.URLField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.trip')),
            ],
        ),
    ]
