# Generated by Django 4.2.23 on 2025-08-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0005_modelsuggestions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsuggestions',
            old_name='activity_url',
            new_name='place_url',
        ),
    ]
