# Generated by Django 4.2.23 on 2025-08-20 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0006_rename_activity_url_modelsuggestions_place_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTripActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location_string', models.CharField(help_text='Raw GPT-provided location string', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='chatgpt', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripActivityDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('wishlist', 'Wishlist'), ('saved', 'Saved'), ('visited', 'Visited'), ('rejected', 'Rejected')], default='wishlist', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_locations', to='mojo_app.modeltripactivity')),
            ],
        ),
        migrations.CreateModel(
            name='TripParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('contributor', 'Contributor'), ('viewer', 'Viewer')], default='contributor', max_length=16)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEnteredActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='modelsuggestions',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='id',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ModelSuggestions',
        ),
        migrations.AddField(
            model_name='userenteredactivity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.trip'),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.trip'),
        ),
        migrations.AddField(
            model_name='tripparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripactivitydetails',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_locations', to='mojo_app.trip'),
        ),
        migrations.AddField(
            model_name='tripactivitydetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modeltripactivity',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='tripparticipant',
            unique_together={('trip', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='tripactivitydetails',
            unique_together={('trip', 'place')},
        ),
        migrations.AddIndex(
            model_name='modeltripactivity',
            index=models.Index(fields=['latitude', 'longitude'], name='mojo_app_mo_latitud_3fffbf_idx'),
        ),
    ]
