# Generated by Django 4.2.23 on 2025-08-20 02:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0009_auto_20250819_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
