# Generated by Django 4.2.23 on 2025-08-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0012_alter_tripactivitydetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripactivitydetails',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('rejected', 'Rejected'), ('blank', 'Blank')], default='blank', max_length=20),
        ),
    ]
