# Generated by Django 4.2.23 on 2025-09-09 01:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mojo_app', '0014_alter_tripactivitydetails_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with', models.EmailField(max_length=254)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mojo_app.trip')),
            ],
            options={
                'unique_together': {('trip', 'shared_with')},
            },
        ),
    ]
